export const CHATS_LIST_REQUEST = 'CHATS_LIST_REQUEST'
export const CHATS_LIST_SUCCESS = 'CHATS_LIST_SUCCESS'
export const CHATS_LIST_FAIL = 'CHATS_LIST_FAIL'

export const CHAT_CREATE_REQUEST = 'CHAT_CREATE_REQUEST'
export const CHAT_CREATE_SUCCESS = 'CHAT_CREATE_SUCCESS'
export const CHAT_CREATE_FAIL = 'CHAT_CREATE_FAIL'

export const CHAT_SINGLE_REQUEST = 'CHAT_SINGLE_REQUEST'
export const CHAT_SINGLE_SUCCESS = 'CHAT_SINGLE_SUCCESS'
export const CHAT_SINGLE_FAIL = 'CHAT_SINGLE_FAIL'